name: test
recipes: "resources/craft/recipes.yaml"
world: 
  name: CraftWorld
model: 
  name: KeyboardModel
  use_args: false
  featurize_plan: true
  max_subtask_timesteps: 15
  baseline: state
trainer: 
  name: CurriculumTrainer
  use_curriculum: false
  improvement_threshold: 0.8
  hints: "resources/craft/hints.yaml"
  max_timesteps: 100
